version: '3'

services:
  olmocr:
    build:
      context: .
      dockerfile: Dockerfile
    image: olmocr:latest
    container_name: olmocr
    volumes:
      - ./input_pdfs:/data/pdfs
      - ./workspace:/data/workspace
    # 暴露sglang服务端口
    ports:
      - "30024:30024"
    # 使用主机网络模式，避免网络问题
    network_mode: "host"
    # 使用GPU资源
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # 默认命令 - 可以根据需要在运行时覆盖
    command: ["/data/workspace", "--pdfs", "/data/pdfs/*.pdf"]
    # 可选：添加环境变量
    environment:
      - PYTHONUNBUFFERED=1
      - SGLANG_ENABLE_CUDA=1 