name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} crpi-7x18vwip50xgw45o.cn-shanghai.personal.cr.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag crpi-7x18vwip50xgw45o.cn-shanghai.personal.cr.aliyuncs.com/jzhu_docker_repo/olmocr:latest
          # 推送镜像到镜像仓库
          docker push crpi-7x18vwip50xgw45o.cn-shanghai.personal.cr.aliyuncs.com/jzhu_docker_repo/olmocr:latest
